# 210706 기초세션

## Numpy

- Numerical Python의 준말
- array(행렬) 기반의 빠른 수치 계산에 유용
- pandas를 비롯한 여러 라이브러리에 호환되는 라이브러리

In [ ]:
# numpy 설치가 되지 않았을 경우 실행
!pip install numpy

In [1]:
import numpy as np
np.__version__

'1.19.2'

### Array(배열)이란?
- numpy에서 사용되는 자료 단위
- 1차원, 2차원, 3차원이 있음.

In [11]:
# 1차원
# 단, 1차원의 배열의 사용은 추천하지 않음
np.array([1,2,3])

array([1, 2, 3])

In [13]:
# 2차원
np.array([[1,2,3],
          [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
# 3차원
np.array([[[1,2,3],
           [4,5,6]],
          [[7,8,9],
           [10,11,12]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### 배열의 속성과 관련 함수

- 배열은 통일된 자료형만 담을 수 있음.

In [16]:
np.array([1,2,'4'])

array(['1', '2', '4'], dtype='<U11')

- 배열 선언 시 자료형 선언 가능
- **dtype**: 배열의 자료형 확인
- **astype**: 배열의 자료형 변환

In [27]:
arr_str = np.array([1,2,3], dtype=str)
arr_flo = np.array([1,2,3], dtype=float)
arr_int = np.array([1,2,3], dtype=int)

# 자료형 확인
print(arr_str.dtype)
print(arr_flo.dtype)
print(arr_int.dtype)

<U1
float64
int32


In [31]:
# 자료형 변환
arr_str = arr_str.astype(int)
arr_str.dtype

dtype('int32')

- **size** : 배열의 원소 수

In [32]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.size

6

- **arange**: range와 유사, 지정한 값 범위의 배열 생성

In [3]:
print(np.arange(1,10))
print(np.arange(1,10,3))
print(np.arange(1,10).reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[1 4 7]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- **ndim**: 배열의 차원 수
- **shape**: 배열의 차원을 튜플로 표시

In [36]:
# 1차원
arr = np.array([1,2,3])

print(arr.ndim)
print(arr.shape)

1
(3,)


In [38]:
# 2차원
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr.ndim)
print(arr.shape) # 행, 열

2
(2, 3)


In [42]:
arr= np.array([[[1,2,3,4],
                [4,5,6,7]],
               [[7,8,9,10],
                [10,11,12,13]],
               [[0,1,2,3],
                [2,3,4,5]]])

print(arr)
print(arr.ndim)
print(arr.shape) # 높이, 행, 열

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 7  8  9 10]
  [10 11 12 13]]

 [[ 0  1  2  3]
  [ 2  3  4  5]]]
3
(3, 2, 4)


- **reshape** : 배열의 형태, 차원을 조정

In [52]:
arr = np.array([[1,2,3],
                [4,5,6]])

arr = arr.reshape(3,2)
print(arr)

[[1 2]
 [3 4]
 [5 6]]


In [68]:
print('1차원으로 변환')
arr = arr.reshape(6,)
print(arr, arr.shape)
print()

print('1차원으로 보이지만 2차원으로 인식됨')
arr = arr.reshape(1,6)
print(arr, arr.shape)
print()

print('3차원으로 변환')
arr = arr.reshape(2,1,3)
print(arr, arr.shape)
print()

1차원으로 변환
[1 2 3 4 5 6] (6,)

1차원으로 보이지만 2차원으로 인식됨
[[1 2 3 4 5 6]] (1, 6)

3차원으로 변환
[[[1 2 3]]

 [[4 5 6]]] (2, 1, 3)



In [69]:
# -1의 사용, 숫자를 정해주지 않아도 자동 조정

arr = np.array([[1,2,3],
                [4,5,6]])
arr.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

기타 생성 함수들
- **ones**: 1로 이루어진 배열
- **zeros**: 0으로 이루어진 배열
- **full**: 지정값으로 이루어진 배열

In [7]:
print(np.ones((2,3)))
print(np.zeros((2,3)))
print(np.full((2,3),4))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[4 4 4]
 [4 4 4]]


### 배열에서 원하는 값 찾기 (슬라이싱, 인덱싱)


- 1차원

In [15]:
arr = np.array([1,2,3,4,5])
print(arr[0:2]) # 첫 번째부터 세 번째까지
print(arr[[0,3]]) # 첫 번째, 네 번째
print(arr[-1]) # 뒤에서 첫 번째

[1 2]
[1 4]
5


- 2차원

In [48]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# arr[행, 열]
a = arr[0:2, 0:2]
print(a)

a2 = arr[1:, 1:]
print(a2)

[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [49]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
print(arr[[0, 2], [1, 2]])
print(arr[0, 2])
print(arr[0][2])

[2 9]
3
3


In [23]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

a3 = arr[0]
print(a3)

a4 = arr[0, ]
print(a4)

a5 = arr[0, :]
print(a5)

[1 2 3]
[1 2 3]
[1 2 3]


In [26]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# a6 = arr[, 0] # error
# print(a6)

a7 = arr[:, 0] # error
print(a7)

a8 = arr[1:, :1]
print(a8)

[1 4 7]
[[4]
 [7]]


- 3차원

In [53]:
# arr[높이, 행, 열]

arr = np.arange(24).reshape(2, 3, 4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [32]:
print(arr[0])
print()
print(arr[:, 0])
print()
print(arr[1, 2, 0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[ 0  1  2  3]
 [12 13 14 15]]

20


In [33]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [56]:
print(arr[1] [[0, 1]] [:, [0, 2]])
print('====================')
print(arr[:, 0:2, 0:2])

[[12 14]
 [16 18]]
[[[ 0  1]
  [ 4  5]]

 [[12 13]
  [16 17]]]


In [54]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [55]:
print(arr[0] [[0, 1], :] [:, [0, 1]])
print()
print(arr[0:1, 0:2, 0:2])

[[0 1]
 [4 5]]

[[[0 1]
  [4 5]]]


- **불린 인덱싱(Boolean indexing)**: 특정 조건으로 값 추출

In [64]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

[False, True, True]

print(arr[[False, True, True], :]) # 2번째, 3번째 행 추출
print(arr[:, [False, True, True]]) # 2번째, 3번째 열 추출

[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [70]:
print(arr[:,1])
print(arr[:,1]>3)
print(arr[arr[:,1]>3, ])

[2 5 8]
[False  True  True]
[[4 5 6]
 [7 8 9]]


### 연산
- numpy는 빠르게 여러 수의 연산이 가능

- 연산자

In [102]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+1)
print(a-1)
print(a*2)
print(a/2)
print(a//2) # 몫
print(a%2) # 나머지
print(a**2) # 제곱
print(2**a)

[2 3 4]
[0 1 2]
[2 4 6]
[0.5 1.  1.5]
[0 1 1]
[1 0 1]
[1 4 9]
[2 4 8]


In [104]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]


함수
- add: 합
- subtract: 차
- multuiply: 곱
- divide: 나눗셈
- power: 승
- modf: 배열 원소의 정수와 소수점을 구분하여 2개의 배열 반환
- mod: 첫 번째 배열의 원소를 두 번째 배열 원소로 나눈 나머지
- abs , fabs: 절댓값
- sqrt: 제곱근
- square: 제곱
- exp: 지수함수(e^)
- log / log10 / lo2:  자연로그 / 상용로그 / 밑이 2인 로그
- sign: 부호

In [118]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([-1, 3, -4])
d = np.array([4.5, 6.3, 7.8, 4.4, 3])
d = np.array([4.5, 6.3, 7.8, 4.4, 3])

print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))
print(np.power(a, b))
print(np.modf(d))
print(np.modf(d)[0])
print(np.modf(d)[1])
print(np.mod(b, a))
print(np.abs(c))
print(np.fabs(c)) # abs보다 속도가 더 빠름
print(np.sqrt(b))
print(b**0.5)
print(np.square(a))
print(a**2)
print(np.exp(a))
print(np.log(a))
print(np.log10(a))
print(np.log2(a))
print(np.sign(c))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
(array([0.5, 0.3, 0.8, 0.4, 0. ]), array([4., 6., 7., 4., 3.]))
[0.5 0.3 0.8 0.4 0. ]
[4. 6. 7. 4. 3.]
[0 1 0]
[1 3 4]
[1. 3. 4.]
[2.         2.23606798 2.44948974]
[2.         2.23606798 2.44948974]
[1 4 9]
[1 4 9]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[-1  1 -1]


- **diff**

In [109]:
arr = np.array([1, 2, 4, 10, 13, 20])
print(arr)
print(np.diff(arr)) # 원소간 1차 차분
print(np.diff(arr, n=2)) # 1차 차분 결과를 가지고 2차 차분
print(np.diff(arr, n=3)) # 2차 차분 결과를 가지고 3차 차분

[ 1  2  4 10 13 20]
[1 2 6 3 7]
[ 1  4 -3  4]
[ 3 -7  7]


In [116]:
arr = np.array([[1, 2, 4, 8], [10, 13, 20, 15]])

print(arr)

print('\n <행끼리 차분>')
print(np.diff(arr, axis=0))

print('\n <열끼리 차분>')
print(np.diff(arr, axis=1))

print('\n <열끼리 2차 차분>')
print(np.diff(arr, n=2, axis=1)) # 2차 차분

[[ 1  2  4  8]
 [10 13 20 15]]

 <행끼리 차분>
[[ 9 11 16  7]]

 <열끼리 차분>
[[ 1  2  4]
 [ 3  7 -5]]

 <열끼리 2차 차분>
[[  1   2]
 [  4 -12]]


- **prod, nanprod**: 전체 곱

In [123]:
b = np.array([1, 2, 3, 4])
print(np.prod(b))

24


In [122]:
c = np.array([[1, 2], [3, 4]])
print(c, '\n')
print(np.prod(c, axis=0), '\n')
print(np.prod(c, axis=1))

[[1 2]
 [3 4]] 

[3 8] 

[ 2 12]


In [125]:
d = np.array([[1, 2], [3, np.nan]])
print(d, '\n')
print(np.nanprod(d, axis=0), '\n')
print(np.nanprod(d, axis=1), '\n')

[[ 1.  2.]
 [ 3. nan]] 

[3. 2.] 

[2. 3.] 



**소수 관련 함수**
- ceil: 올림
- floor: 내림
- round_: 반올림하여 소수점 이하 n번째 자리까지 표현
- fix: '0'방향으로 가장 가까운 정수로 올림 혹은 내림
- trunc: 소수점 버림

In [129]:
a = np.array([-4.62, -2.19, 0, 1.57, 3.40, 4.06])

print(np.ceil(a))
print(np.floor(a))
print(np.round_(a, 1))

[-4. -2.  0.  2.  4.  5.]
[-5. -3.  0.  1.  3.  4.]
[-4.6 -2.2  0.   1.6  3.4  4.1]


In [130]:
print(np.fix(a))
print(np.trunc(a))

[-4. -2.  0.  1.  3.  4.]
[-4. -2.  0.  1.  3.  4.]


**통계함수**
- sum: 합
- mean: 평균
- std/var: 표준편차/분산
- min/max: 최소/최대
- argmin/ argmax: 최소/최댓값의 위치

In [143]:
arr = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(arr)
print('차원:', arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
차원: (3, 3)


In [145]:
print('전체 합', arr.sum())
print()
print('행끼리 더함\n', arr.sum(axis=0))
print()
print('열끼리 더함\n', arr.sum(axis=1))

전체 합 45

행끼리 더함(같은 열 안에서 더함)
 [12 15 18]

열끼리 더함(같은 행 안에서 더함)
 [ 6 15 24]


In [148]:
arr= np.array([[[1,2,3,4],
                [4,5,6,7]],
               [[7,8,9,10],
                [10,11,12,13]]])

print(arr)
print('차원:', arr.shape)

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 7  8  9 10]
  [10 11 12 13]]]
차원: (2, 2, 4)


In [150]:
print('전체 합', arr.sum())
print()
print('배열끼리 더함\n', arr.sum(axis=0))
print()
print('행끼리 더함(같은 열 안에서 더함)\n', arr.sum(axis=1))
print()
print('열끼리 더함(같은 행 안에서 더함)\n', arr.sum(axis=2))

전체 합 112

배열끼리 더함
 [[ 8 10 12 14]
 [14 16 18 20]]

행끼리 더함(같은 열 안에서 더함)
 [[ 5  7  9 11]
 [17 19 21 23]]

열끼리 더함(같은 행 안에서 더함)
 [[10 22]
 [34 46]]


In [154]:
a = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print(a.std(axis=0))
print(a.var(axis=0))
print(a.max(axis=0))
print(a.min(axis=0))
print(a.argmax(axis=0))
print(a.argmin(axis=0))

[2.44948974 2.44948974 2.44948974]
[6. 6. 6.]
[7 8 9]
[1 2 3]
[2 2 2]
[0 0 0]


기타 함수들
- sort: 정렬

In [159]:
arr = np.array([4,1,6,2,7])
arr.sort()
arr

array([1, 2, 4, 6, 7])

- unique: 중복 원소 제외 (pandas에도 가능)

In [162]:
arr = np.array([6,6,6,6,6])
np.unique(arr)

array([6])

- T: 전치

In [163]:
arr = np.array([[1,2],[3,4],[5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [164]:
arr.T

array([[1, 3, 5],
       [2, 4, 6]])

논리연산
- isnan: 결측값이면 True
- isinf: 무한값이면 True
- equal: 두 배열이 같으면 True
- any: 하나라도 True이면 True
- all: 모두 True이면 True

In [172]:
a = np.array([[0, 1, 2], 
             [np.nan, 4, np.inf]])

print(np.isnan(a))
print(np.isinf(a))

[[False False False]
 [ True False False]]
[[False False False]
 [False False  True]]


In [174]:
a = np.array([1,2,3])
b = np.array([1,2,3])

np.equal(a,b)

array([ True,  True,  True])

In [178]:
arr = np.array([True, True, False])
print(np.any(arr))
print(np.all(arr))

True
False


### 병합과 분할

병합
- vstack: 세로로 붙이기
- hstack: 가로로 붙이기

In [182]:
arr1 = np.array([[1,2,3],
               [4,5,6]])
arr2 = np.array([[7,8,9],
               [10,11,12]])
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [184]:
np.vstack([arr1, arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [185]:
np.hstack([arr1, arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

분할
- vsplit: 세로로 나누기
- hsplit: 가로로 나누기

In [186]:
arr1 

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
np.vsplit(arr1,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [192]:
np.hsplit(arr1,3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

## Pandas
- Excel을 파이썬으로
- 자료 전처리, EDA에서 주로 활용

In [ ]:
# pandas 미설치시 실행
!pip install pandas

In [193]:
import pandas as pd
pd.__version__

'1.1.3'

### Series와 DataFrame
- Series가 모여서 DataFrame을 구성

In [194]:
s = pd.Series([1,2,3,4],
             index=['a','b','c','d'],
             name='number')

s

a    1
b    2
c    3
d    4
Name: number, dtype: int64

In [198]:
print(s.values)
print(s.index)
print(s.name)
print(s.dtype)

[1 2 3 4]
Index(['a', 'b', 'c', 'd'], dtype='object')
number
int64


In [352]:
val = np.array([[1,2,3],
             [4,5,6]])

df = pd.DataFrame(data=val, 
                  index=['a','b'],
                 columns=['first', 'second','third'])
df

first  second  third
a      1       2      3
b      4       5      6

In [208]:
print(df.values, '\n')
print(df.index, '\n')
print(df.columns, '\n')
print(df.dtypes, '\n')
print(df.shape, '\n')

[[1 2 3]
 [4 5 6]] 

Index(['a', 'b'], dtype='object') 

Index(['first', 'second', 'third'], dtype='object') 

first     int32
second    int32
third     int32
dtype: object 



In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, a to b
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   first   2 non-null      int32
 1   second  2 non-null      int32
 2   third   2 non-null      int32
dtypes: int32(3)
memory usage: 40.0+ bytes


In [ ]:
df.head()
df.tail()

### 원하는 값 찾기
#### iloc: 숫자 기반 인덱싱

In [222]:
df

first  second  third
a      1       2      3
b      4       5      6

In [233]:
df.iloc[0,1] #[행, 열]
df.iloc[0:,0:2]
df.iloc[0:,[0,2]]
df.iloc[:,:-1]

first  second
a      1       2
b      4       5

#### loc: 명칭 기반 인덱싱

In [235]:
df

first  second  third
a      1       2      3
b      4       5      6

In [240]:
df.loc['a','second']
df.loc['a':,'first':'second']
df.loc['a':,['first','third']]

first  second
a      1       2
b      4       5

- 열은 간단하게 호출 가능(행은 안됨)

In [248]:
df['third']
df.third

a    3
b    6
Name: third, dtype: int32

#### 불린 인덱싱

In [261]:
df

first  second  third
a      1       2      3
b      4       5      6

In [263]:
df['second']%2 == 0

a     True
b    False
Name: second, dtype: bool

In [264]:
df[df['second']%2 == 0]

first  second  third
a      1       2      3

In [266]:
df['first'] > 2

a    False
b     True
Name: first, dtype: bool

In [265]:
df[df['first'] > 2]

first  second  third
b      4       5      6

### 데이터프레임 수정

- reindex: 행/열 순서 바꾸기

In [210]:
df

first  second  third
a      1       2      3
b      4       5      6

In [211]:
df.reindex(['b','a'], axis=0)

first  second  third
b      4       5      6
a      1       2      3

In [215]:
df.reindex(['third','second','first'], axis=1)

third  second  first
a      3       2      1
b      6       5      4

- columns, index: 열/행 이름 바꾸기

In [216]:
df

first  second  third
a      1       2      3
b      4       5      6

In [217]:
df.index = ['one', 'two']
df

first  second  third
one      1       2      3
two      4       5      6

In [353]:
df.columns = ['일', '이', '삼']
df

일  이  삼
a  1  2  3
b  4  5  6

In [355]:
df.rename({'일':'첫째'}, axis=1)

첫째  이  삼
a   1  2  3
b   4  5  6

In [356]:
df.rename({'a':'A'}, axis=0)

일  이  삼
A  1  2  3
b  4  5  6

- 행/열 추가

In [390]:
df = pd.DataFrame(data=val, 
                  index=['a','b'],
                 columns=['first', 'second','third'])
df

first  second  third
a      1       2      3
b      4       5      6

In [392]:
# 새로운 열 추가
df['fourth']=[4,7]
df

df['fifth']=df['first']+df['second']
df

first  second  third  fourth  fifth
a      1       2      3       4      3
b      4       5      6       7      9

In [251]:
# 새로운 행 추가
df.loc['c',:]=[8,9,10,11]
df

first  second  third  fourth
a    1.0     2.0    3.0     4.0
b    4.0     5.0    6.0     7.0
c    8.0     9.0   10.0    11.0

### 데이터프레임 삭제
- drop을 사용

In [252]:
df.drop(['third','fourth'], axis=1)

first  second
a    1.0     2.0
b    4.0     5.0
c    8.0     9.0

In [254]:
df

first  second  third  fourth
a    1.0     2.0    3.0     4.0
b    4.0     5.0    6.0     7.0
c    8.0     9.0   10.0    11.0

In [255]:
df.drop(['third','fourth'], axis=1, inplace=True)

In [256]:
df

first  second
a    1.0     2.0
b    4.0     5.0
c    8.0     9.0

In [257]:
df.drop(['b'], axis=0, inplace=True)

In [258]:
df

first  second
a    1.0     2.0
c    8.0     9.0

In [259]:
# 데이터프레임 삭제
del df

### 결측값 확인과 처리

In [290]:
val = np.array([1.0, np.nan, 3.5, 6.1, np.nan, 7.0,10,9,8]).reshape(3,-1)
df = pd.DataFrame(val, columns=['a','b','c'])
df

a    b    c
0   1.0  NaN  3.5
1   6.1  NaN  7.0
2  10.0  9.0  8.0

In [291]:
# 결측값 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      float64
 1   b       1 non-null      float64
 2   c       3 non-null      float64
dtypes: float64(3)
memory usage: 200.0 bytes


In [292]:
df.isnull()

a      b      c
0  False   True  False
1  False   True  False
2  False  False  False

In [293]:
df.isnull().sum(axis=1)
df.isnull().sum(axis=0)

a    0
b    2
c    0
dtype: int64

In [276]:
df.dropna(axis=0, how='any')

0    1    2
2  10.0  9.0  8.0

In [280]:
df.dropna(axis=1, how='any')

0    2
0   1.0  3.5
1   6.1  7.0
2  10.0  8.0

In [281]:
df.dropna(axis=1, how='all')

0    1    2
0   1.0  NaN  3.5
1   6.1  NaN  7.0
2  10.0  9.0  8.0

In [282]:
df.fillna(10000)

0        1    2
0   1.0  10000.0  3.5
1   6.1  10000.0  7.0
2  10.0      9.0  8.0

### 정렬

In [399]:
df = pd.DataFrame([[1,5,0,-1],[10,7,100,99],[10,10,2,-50]], columns=['b','a','c','d'], index=[2,3,1])
df

b   a    c   d
2   1   5    0  -1
3  10   7  100  99
1  10  10    2 -50

- sort_index: 행/열 기준으로 정렬

In [400]:
df.sort_index(axis=0)

b   a    c   d
1  10  10    2 -50
2   1   5    0  -1
3  10   7  100  99

In [401]:
df.sort_index(axis=1)

a   b    c   d
2   5   1    0  -1
3   7  10  100  99
1  10  10    2 -50

- sort_values: 값 기준으로 정렬

In [402]:
df

b   a    c   d
2   1   5    0  -1
3  10   7  100  99
1  10  10    2 -50

In [403]:
df.sort_values(by=['c'],axis=0)

b   a    c   d
2   1   5    0  -1
1  10  10    2 -50
3  10   7  100  99

In [406]:
df.sort_values(by=['c'],axis=0,ascending=False)

b   a    c   d
3  10   7  100  99
1  10  10    2 -50
2   1   5    0  -1

In [405]:
df.sort_values(by=['b','c'],axis=0)

b   a    c   d
2   1   5    0  -1
1  10  10    2 -50
3  10   7  100  99

In [313]:
df.sort_values(by=[3],axis=1)

a   b    c
2  5   1    0
3  7  10  100
1  2  10  -50

### 병합
#### concat
- 단순한 병합 시 사용

In [316]:
df_1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2'],
                    'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']},
                 index=[0, 1, 2])
df_1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

In [317]:
df_2 = pd.DataFrame({'A': ['A3', 'A4', 'A5'],
                    'B': ['B3', 'B4', 'B5'],
                    'C': ['C3', 'C4', 'C5'],
                    'D': ['D3', 'D4', 'D5']},
                    index=[3, 4, 5])
df_2

A   B   C   D
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [321]:
pd.concat([df_1, df_2], axis=0) # 세로로 결합(행끼리)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5

In [322]:
pd.concat([df_1, df_2], axis=1) # 인덱스가 같아야 함

A    B    C    D    A    B    C    D
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN   A3   B3   C3   D3
4  NaN  NaN  NaN  NaN   A4   B4   C4   D4
5  NaN  NaN  NaN  NaN   A5   B5   C5   D5

In [323]:
df_2.index = [0,1,2]
pd.concat([df_1, df_2], axis=1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A3  B3  C3  D3
1  A1  B1  C1  D1  A4  B4  C4  D4
2  A2  B2  C2  D2  A5  B5  C5  D5

#### merge
- key/index를 기준으로 병합

In [325]:
df_1 = pd.DataFrame({'id':[1,2,3,4], 'name':['kim','jo','park','lee']})
df_2 = pd.DataFrame({'id':[3,4,5,6], 'score':[100,40,23,45]})

df_1

id  name
0   1   kim
1   2    jo
2   3  park
3   4   lee

In [326]:
df_2

id  score
0   3    100
1   4     40
2   5     23
3   6     45

In [333]:
pd.merge(df_1, df_2, left_on='id', right_on='id', how='inner')
# pd.merge(df_1, df_2, left_on='id', right_on='id', how='left')
# pd.merge(df_1, df_2, left_on='id', right_on='id', how='right')
# pd.merge(df_1, df_2, left_on='id', right_on='id', how='outer')

id  name  score
0   3  park    100
1   4   lee     40

In [337]:
df_1 = pd.DataFrame({'name':['kim','jo','park','lee']}, index=['a','b','c','d'])
df_2 = pd.DataFrame({'id':['c','d','e','f'], 'score':[100,40,23,45]})
df_1

name
a   kim
b    jo
c  park
d   lee

In [339]:
df_2

id  score
0  c    100
1  d     40
2  e     23
3  f     45

In [338]:
pd.merge(df_1, df_2, left_index=True, right_on='id', how='inner')
pd.merge(df_1, df_2, left_index=True, right_on='id', how='left')
pd.merge(df_1, df_2, left_index=True, right_on='id', how='right')
pd.merge(df_1, df_2, left_index=True, right_on='id', how='outer')

name id  score
0  park  c    100
1   lee  d     40

### 파일 읽기/저장하기

In [385]:
df = pd.DataFrame({'학급':[1,1,1,1,2,2,2,2],
                   '시험':['mathmatics','mathmatics','english','english','mathmatics','english','mathmatics','english'],
                   '점수':[10,40,50,24,25,10,20,34]})
df

학급          시험  점수
0   1  mathmatics  10
1   1  mathmatics  40
2   1     english  50
3   1     english  24
4   2  mathmatics  25
5   2     english  10
6   2  mathmatics  20
7   2     english  34

In [386]:
df.to_csv('session.csv', index=False,encoding='CP949') # utf-8

In [387]:
pd.read_csv('session.csv', encoding='CP949')

학급          시험  점수
0   1  mathmatics  10
1   1  mathmatics  40
2   1     english  50
3   1     english  24
4   2  mathmatics  25
5   2     english  10
6   2  mathmatics  20
7   2     english  34

In [388]:
df.to_csv('session.csv', index=True,encoding='CP949') 
pd.read_csv('session.csv', encoding='CP949')

Unnamed: 0  학급          시험  점수
0           0   1  mathmatics  10
1           1   1  mathmatics  40
2           2   1     english  50
3           3   1     english  24
4           4   2  mathmatics  25
5           5   2     english  10
6           6   2  mathmatics  20
7           7   2     english  34

### 기타 응용(전처리)

#### groupby
- 집계함수 sum, mean, count 등을 이용해 데이터를 가공할 수 있음

In [367]:
df = pd.DataFrame({'class':[1,1,1,1,2,2,2,2],
                   'exam':['mathmatics','mathmatics','english','english','mathmatics','english','mathmatics','english'],
                   'score':[10,40,50,24,25,10,20,34]})

In [368]:
df

class        exam  score
0      1  mathmatics     10
1      1  mathmatics     40
2      1     english     50
3      1     english     24
4      2  mathmatics     25
5      2     english     10
6      2  mathmatics     20
7      2     english     34

In [369]:
df.groupby('class').mean()

score
class       
1      31.00
2      22.25

In [370]:
df.groupby(['class','exam']).mean()

score
class exam             
1     english      37.0
      mathmatics   25.0
2     english      22.0
      mathmatics   22.5

In [371]:
# 시각화 시 유용
df.groupby(['class','exam']).mean().reset_index()

class        exam  score
0      1     english   37.0
1      1  mathmatics   25.0
2      2     english   22.0
3      2  mathmatics   22.5

In [372]:
df.groupby(['class']).agg({'score':'sum', 'exam':'count'})

score  exam
class             
1        124     4
2         89     4

#### pivot_table

In [373]:
df

class        exam  score
0      1  mathmatics     10
1      1  mathmatics     40
2      1     english     50
3      1     english     24
4      2  mathmatics     25
5      2     english     10
6      2  mathmatics     20
7      2     english     34

In [1]:
pd.pivot_table(df, index='class', columns='exam', value='score', aggfunc='sum')

NameError: name 'pd' is not defined

#### map

In [376]:
df

class        exam  score
0      1  mathmatics     10
1      1  mathmatics     40
2      1     english     50
3      1     english     24
4      2  mathmatics     25
5      2     english     10
6      2  mathmatics     20
7      2     english     34

In [377]:
df.exam.map(lambda x:x[:4])

0    math
1    math
2    engl
3    engl
4    math
5    engl
6    math
7    engl
Name: exam, dtype: object

In [379]:
df.score / df.score.max() * 100

0     20.0
1     80.0
2    100.0
3     48.0
4     50.0
5     20.0
6     40.0
7     68.0
Name: score, dtype: float64